/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "#ffdf93",
        "secondary-fixed": "#e9ddff",
        "on-surface-variant": "#cbc4d2",
        "on-tertiary-fixed-variant": "#594400",
        "on-primary-fixed-variant": "#4f378a",
        "on-error": "#690005",
        "on-secondary": "#342b4b",
        "outline": "#948e9c",
        "primary": "#cfbcff",
        "primary-container": "#6750a4",
        "inverse-surface": "#e6e0e9",
        "tertiary-fixed-dim": "#e7c365",
        "secondary-fixed-dim": "#cdc0e9",
        "surface-container-lowest": "#0f0d13",
        "surface": "#141218",
        "background": "#141218",
        "secondary": "#cdc0e9",
        "inverse-primary": "#6750a4",
        "on-secondary-container": "#bfb2da",
        "on-error-container": "#ffdad6",
        "surface-variant": "#36343a",
        "primary-fixed-dim": "#cfbcff",
        "on-secondary-fixed-variant": "#4b4263",
        "inverse-on-surface": "#322f35",
        "secondary-container": "#4d4465",
        "surface-dim": "#141218",
        "surface-bright": "#3b383e",
        "error": "#ffb4ab",
        "on-primary": "#381e72",
        "outline-variant": "#494551",
        "surface-tint": "#cfbcff",
        "tertiary-container": "#c9a74d",
        "surface-container-high": "#2b292f",
        "on-tertiary-container": "#503d00",
        "surface-container-highest": "#36343a",
        "on-secondary-fixed": "#1f1635",
        "on-surface": "#e6e0e9",
        "primary-fixed": "#e9ddff",
        "surface-container-low": "#1d1b20",
        "tertiary": "#e7c365",
        "error-container": "#93000a",
        "on-primary-container": "#e0d2ff",
        "on-tertiary": "#3e2e00",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed": "#22005d",
        "surface-container": "#211f24",
        "on-background": "#e6e0e9"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "unit": "8px",
        "stack-sm": "12px",
        "margin-page": "48px",
        "stack-lg": "48px",
        "container-max": "1440px",
        "stack-md": "24px",
        "gutter": "24px"
      },
      "fontSize": {
        "section-title": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-main": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "button-text": ["14px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "hero-display": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
