/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "#f1f5f9",
        "secondary-fixed": "#e2e8f0",
        "on-surface-variant": "#64748b",
        "on-tertiary-fixed-variant": "#1e293b",
        "on-primary-fixed-variant": "#0f172a",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#e2e8f0",
        "primary": "#0f172a",
        "primary-container": "#f1f5f9",
        "inverse-surface": "#0f172a",
        "tertiary-fixed-dim": "#cbd5e1",
        "secondary-fixed-dim": "#94a3b8",
        "surface-container-lowest": "#ffffff",
        "surface": "#ffffff",
        "background": "#f8fafc",
        "secondary": "#64748b",
        "inverse-primary": "#ffffff",
        "on-secondary-container": "#0f172a",
        "on-error-container": "#000000",
        "surface-variant": "#f1f5f9",
        "primary-fixed-dim": "#0f172a",
        "on-secondary-fixed-variant": "#475569",
        "inverse-on-surface": "#ffffff",
        "secondary-container": "#f1f5f9",
        "surface-dim": "#f1f5f9",
        "surface-bright": "#ffffff",
        "error": "#ef4444",
        "on-primary": "#ffffff",
        "outline-variant": "#f1f5f9",
        "surface-tint": "#0f172a",
        "tertiary-container": "#f1f5f9",
        "surface-container-high": "#f8fafc",
        "on-tertiary-container": "#0f172a",
        "surface-container-highest": "#e2e8f0",
        "on-secondary-fixed": "#0f172a",
        "on-surface": "#0f172a",
        "primary-fixed": "#0f172a",
        "surface-container-low": "#ffffff",
        "tertiary": "#94a3b8",
        "error-container": "#fee2e2",
        "on-primary-container": "#000000",
        "on-tertiary": "#000000",
        "on-tertiary-fixed": "#0f172a",
        "on-primary-fixed": "#f8fafc",
        "surface-container": "#f1f5f9",
        "on-background": "#0f172a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "unit": "8px",
        "stack-sm": "12px",
        "margin-page": "48px",
        "stack-lg": "48px",
        "container-max": "1440px",
        "stack-md": "24px",
        "gutter": "24px"
      },
      "fontSize": {
        "section-title": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-main": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "button-text": ["14px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "hero-display": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
